#version 450 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


layout(binding = 0) writeonly uniform image2D uOutput;
layout(binding = 1) uniform sampler2D uInput;

void main() {
    ivec2 texCoord = ivec2(gl_GlobalInvocationID);

    // Fetch data from RGBA texture memory and perform element-wise addition
    vec4 a = texelFetch(uInput, texCoord, 0);
    vec4 ret = floor(a);

    // Write the result to the output RGBA texture
    imageStore(uOutput, texCoord, ret);
}
