#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) writeonly uniform image2DArray uOutput;
layout(set = 0, binding = 1) uniform sampler2DArray uInput;

// sigmoid f(x) = 1 / (1 + exp(-x))
void main() {
    ivec3 coord = ivec3(gl_GlobalInvocationID);
    vec4 inputValue = texelFetch(uInput, coord, 0);
    vec4 outputValue = vec4(1.0)/(vec4(1.0) + exp(-inputValue));
    imageStore(uOutput, coord, outputValue);
}